### ISSUE TITLE
Запрос на внесение дополнительной функции в требования

### ISSUE THREAD

**Issue by Nikomika** [Nikomika/qa_samopodgotovka#2]
Прошу добавить в требовниях дополнительное сообщение, при нажатии кнопки "Удалить" в форме ввода проекта и в форме ввода задачи: «Вы действительно хотите удалить проект/задачу?». Для уменьшения количества ошибок со стороны пользователя.

**Comment by tretsiakova** [comment]
Необходимо описать несколько запросов на уточнение требований, тут больше походит на импрувмент.
