### ISSUE TITLE
Формы ввода в режиме добавления: отсутствует поле "Идентификатор"

### ISSUE THREAD

**Issue by Nikomika** [Nikomika/qa_samopodgotovka#5]
**Места воспроизведения:**

Форма ввода проекта в режиме добавления;
Колонки таблицы "Список задач, принадлежащих проекту" на форме ввода проекта в режиме добавления;
Форма ввода задачи в режиме добавления;
Форма ввода персоны в режиме добавления.

**Шаги воспроизведения для формы ввода проекта в режиме добавления:**

1. В главном меню выбрать "Проекты";
2. Нажать кнопку "Добавить", внизу страницы;
3. Обратить внимание на количество полей на форме.

**Полученно:** 
Отсутствует поле "Идентификатор".
**Ожидаемо:** 
Отображается поле "Идентификатор".
**Ссылка на требования:**
См. СПТ пункт 5.Форма ввода проекта.Поля.Идентификатор
См. СПТ пункт 5.Форма ввода проекта.Поля.Список задач, принадлежащих проекту.Колонки.Идентификатор
См. СПТ пункт 6.Форма ввода задачи.Поля.Идентификатор
См. СПТ пункт 7.Форма ввода персоны.Поля.Идентификатор

**Comment by tretsiakova** [comment]
1. В заголовке слово "Идентификатор" необходимо взять в кавычки, слово "Отсутствует" необходимо писать прописными символами
2. Описание в данном случае излишне, предусловие тоже, так как в нем не требуются никакие подготовительные шаги/определенное состояние системы
2. 1 шаг воспроизведения можно тут так же опустить, так как дефект не связан с запуском и установкой приложения
3. Каким образом мы открываем форму "Список проектов"? Лучше более контрено описать  шаг 2
4. В 3 шаге название кнопки необходимо взять в кавычки
5. В получено и ожидаемо можно не дублировать информацию о том, на какой форме отсутствует/отображается поле, так как это отражено в заголовке, так же название поля нужно взять в кавычки
6. В ожидаемо слово "присутствует" лучше заменить на "Отображается"
7. В ссылке на СПТ необходимо указать не только пункт раздела, но и само название раздела, так как нумерация разделов может измениться
