### ISSUE TITLE
"Список проектов": отображается буква "е" в названии колонки "Сокращённое название"

### ISSUE THREAD

**Issue by Nikomika** [Nikomika/qa_samopodgotovka#6]
**Шаги воспроизведения:**

1. В главном меню выбрать "Проекты";
2. Обратить внимание на название третьей колонки.

**Получено:** 
Отображается буква "е" в названии колонки "Сокращённое название".
**Ожидаемо:** 
Отображается буква "ё" в названии колонки "Сокращённое название".
**Ссылка на требования:**
См. СПТ пункт 2.Форма "Список проектов".Колонки.Сокращённое название

**Comment by tretsiakova** [comment]
См. замечания к [#5](https://github.com/Nikomika/qa_samopodgotovka/issues/5)
