### ISSUE TITLE
 Выводится текст об ошибке при сохранении допустимого символа "Ё"

### ISSUE THREAD

**Issue by Nikomika** [Nikomika/qa_samopodgotovka#7]
**Места воспроизведения:** 
Поля на форме ввода проекта: "Название", "Сокращённое название", "Описание"; 
Поля на форме ввода задачи: "Название";
Поля на форме ввода персоны: "Имя", "Фамилия", "Отчество", "Должность". 

**Шаги воспроизведения для поля "Название" на форме ввода проекта в режиме добавления:**

1. В главном меню выбрать "Проекты";
2. Нажать кнопку "Добавить", внизу страницы;
3. Ввести в текстовое поле текст "ЕЩЁ", обязательно в верхнем регистре;
4. Заполнить остальные поля валидными данными
5. Нажать кнопку "Сохранить"

**Получено:** 
Запись не сохраняется. Выводится текст об ошибке: "Название содержит недопустимый символ". 
**Ожидаемо:** 
Запись сохраняется.
**Ссылка на требования:** 
См. СПТ пункт 5.Форма ввода проекта.Поля.Название
См. СПТ пункт 5.Форма ввода проекта.Поля.Сокращённое название
См. СПТ пункт 5.Форма ввода проекта.Поля.Описание
См. СПТ пункт 6.Форма ввода задачи.Поля.Название
См. СПТ пункт 7.Форма ввода персоны.Поля.Имя
См. СПТ пункт 7.Форма ввода персоны.Поля.Фамилия
См. СПТ пункт 7.Форма ввода персоны.Поля.Отчество
См. СПТ пункт 7.Форма ввода персоны.Поля.Должность

**Comment by tretsiakova** [comment]
1. См. замечания к #5
2. Если дефект воспроизводится в нескольких местах, то имеет смысл выносить данную информацию в описание, чтобы не дублировать это в заголовке, исходя из этого нужно доработать описание и заголовок + см. пункт 1
